In [3]:
import pandas as pd

df = pd.read_csv('Value_of_Energy_Cost_Savings_Program_Savings_for_Businesses_-_FY2020.csv')
df

,Company Name,company contact,company email,company phone,Address,City,State,Postcode,Industry,Industry descr,...,Savings from beginning receiving benefits,Borough,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
0,1 State Street,David Neiburg,eskoblo@energyspec.com,7186779077,1114 Avenue J,Brooklyn,NY,11230,Commercial,35 story building,...,349.78,Brooklyn,40.624784,-73.964920,314.0,44.0,534.0,3179818.0,3.067130e+09,Midwood
1,100 Church LLC,Edward A. Carroll,NaN,2125663000,100 Church Street,NY,NY,10007,Commercial,21 Floors,...,4423698.05,New York,40.712968,-74.009490,101.0,1.0,21.0,1001409.0,1.001250e+09,SoHo-TriBeCa-Civic Center-Little Italy
2,100 Wall Investments,Jerry Branam,NaN,2122487160,96 Wall Street,New York,NY,10005,Landlord,NaN,...,1814542.62,New York,40.705052,-74.007199,101.0,1.0,7.0,1000875.0,1.000380e+09,Battery Park City-Lower Manhattan
3,1-10 Bush Terminal Owner LP,Andrew Kimball,akimball@industrycity.com,3474178429,"220 36th St, Suite 2A",Brooklyn,NY,11232,Landlord,Special Eligible Premises for eligible businesses,...,6755.31,Brooklyn,40.656061,-74.007334,307.0,38.0,2.0,3398687.0,3.006950e+09,Sunset Park West
4,"120 Broadway Acquisitions JV, LLC (Ldmk)",Carl Letich,clettich@silvprop.com,2124064020,120 Broadway,New York,NY,10271,Commercial,NaN,...,3293055.08,New York,40.708546,-74.011041,101.0,1.0,7.0,1001026.0,1.000478e+09,Battery Park City-Lower Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,"WONTON FOOD, INC.",DONALD LAU,donaldlau@wontonfood.com,7186286868,220-222 MOORE STREET,Brooklyn,NY,11206,Manufacturing,"MFG. PASTA, EGGROLL SKINS",...,965843.58,Brooklyn,40.704425,-73.936010,301.0,34.0,485.0,3071539.0,3.031090e+09,Bushwick South
446,Wood Works,Gordon Brawm,brawnworks@gmail.com,9179404950,162 Cook Street,Brooklyn,NY,11206,Manufacturing,Installer of wood furniture,...,3585.40,Brooklyn,40.702869,-73.936466,301.0,34.0,485.0,3071625.0,3.031230e+09,Bushwick South
447,"WorldWide Plumbing Supply, Inc.",Surie Lefkowitz,sheidya@wwps.com,7188533002,125 Lake Avenue,Staten Island,NY,10303,Manufacturing,"Plumbing Fixtures, Parts & Supplies, Plumbers",...,20487.73,Staten Island,40.633518,-74.150942,501.0,49.0,239.0,5107122.0,5.011610e+09,Mariner's Harbor-Arlington-Port Ivory-Granitev...
448,WUD Furniture LLC,Keren Springer,keren@wudfurniture.com,7184867952,1102 Atlantic Avenue,Brooklyn,NY,11238,Manufacturing,"We make handcrafted furniture, surfaces, lighting",...,12287.32,Brooklyn,40.679518,-73.956819,308.0,35.0,305.0,3027572.0,3.011260e+09,Crown Heights North
449,Wurtec Incorporated,Bill Popp,bill.popp@wurtec.com,4197261066,31-50 31st Street,Lond Island City,NY,11106,Wholesale/Warehouse/Distribution,Elevator tooling products,...,0.00,Queens,40.763148,-73.924442,401.0,22.0,61.0,4007562.0,4.005890e+09,Astoria

In [4]:
# How many different companies are represented in the data set?

# counting the number of diifferent (unique) companies are represented in the data set

df_unique = df['Company Name'].nunique()
df_unique

439

In [5]:
df.dtypes

Company Name                                  object
company contact                               object
company email                                 object
company phone                                 object
Address                                       object
City                                          object
State                                         object
Postcode                                       int64
Industry                                      object
Industry descr                                object
Company Type                                  object
Current fulltime                             float64
Job created                                  float64
Job retain                                   float64
Effective Date                                object
Total Savings                                float64
Savings from beginning receiving benefits    float64
Borough                                       object
Latitude                                     float64
Longitude                                    float64
Community Board                              float64
Council District                             float64
Census Tract                                 float64
BIN                                          float64
BBL                                          float64
NTA                                           object
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 26 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Company Name                               450 non-null    object
 1   company contact                            450 non-null    object
 2   company email                              433 non-null    object
 3   company phone                              450 non-null    object
 4   Address                                    450 non-null    object
 5   City                                       450 non-null    object
 6   State                                      450 non-null    object
 7   Postcode                                   450 non-null    int64
 8   Industry                                   450 non-null    object
 9   Industry descr                             434 non-null    object
 10  Company Type                               450 non-null    object
 11  Current fulltime                           446 non-null    float64
 12  Job created                                11 non-null     float64
 13  Job retain                                 14 non-null     float64
 14  Effective Date                             450 non-null    object
 15  Total Savings                              450 non-null    float64
 16  Savings from beginning receiving benefits  450 non-null    float64
 17  Borough                                    450 non-null    object
 18  Latitude                                   409 non-null    float64
 19  Longitude                                  409 non-null    float64
 20  Community Board                            409 non-null    float64
 21  Council District                           409 non-null    float64
 22  Census Tract                               409 non-null    float64
 23  BIN                                        401 non-null    float64
 24  BBL                                        401 non-null    float64
 25  NTA                                        409 non-null    object
dtypes: float64(12), int64(1), object(13)
memory usage: 91.5+ KB

In [7]:
df.shape

(450, 26)

In [8]:
# What is the total number of jobs created for businesses in Queens?

result = df.loc[df["City"]=="Queens",["Job created"]]
result.sum()

Job created    90.0
dtype: float64

In [9]:
# How many different unique email domains names are there in the data set?

# nan_values = df['company email'].isna().sum()
# print(nan_values)

# not_nan_values = df['company email'].notna().sum()
# print(not_nan_values)

unique_emails = df['company email'].nunique()
print(unique_emails)

420

In [10]:
# Considering only NTAs with at least 5 listed businesses, what is the average total savings and the total jobs created for each NTA?

#df["NTA"]
filtered_df = df[df["NTA"].str.contains('-',na=False)]

#filtered_df['NTA'].str.count('-').sum()

count_strings = filtered_df[filtered_df['NTA'].apply(lambda x: len(x.split('-'))>=4)]
print(count_strings)

                                    Company Name          company contact  \
1                                 100 Church LLC        Edward A. Carroll
7    141 Lake Avenue Realty c/o JR Produce, Inc.                Josef Raz
16                                 55 Water, LLC            Jermy Frenkel
17                       72andSunny Partners LLC          Mitchell Gendel
46                 American Transit Insurance Co  Edward T McGettigan Jr.
54                           Armada New York LLC              Cory Watson
84                  Bronx River Media Group, LLC            John Battista
96                            Casual Films, Inc.             Barnaby Cook
98                              Chase Bank, N.A.          Edward P Rooney
119                             D.S. & Durga LLC             Kavita Ahuja
129               Deutsche Bank Securities, Inc.   Chandra Gopalakrishnan
151                            Evergreen 105 LLC            Michael Berry
164               Fidelity Payment Services Ltd.          Uri Kunstlinger
177                                  gCreate LLC                 Anna Lee
178  Global Container Terminal (GCT) New York LP            Thomas Fallon
179                            Globus Cork, Inc.          Jennifer Biscoe
182                         GOTHAM SEAFOOD CORP.             John McGuire
193                     HALE & HEARTY SOUPS, LLC             Simon Jacobs
194                      Hall Street Storage LLC             Jeffrey Sitt
208                           HUSH Studios, Inc.            David Schwarz
222          JAMES CARPENTER DESIGN ASSOC., INC.            DIANE CHILLOG
252                           Lafayette 148, Inc               Thomas Hoi
267          MADELAINE CHOCOLATE NOVELTIES, INC.              Norman Gold
296                       New Concepts of NY LLC          Robert Schwartz
305                             Noho Health, Inc                Aman Raju
311                          NY Telephone #11194               Quin Quinn
326                            PetCare Rx., Inc.     Vijay Manthripragada
329                         Picture Farm II, LLC            Monae Freeman
338                         R Simon Design, Inc.           Jasmine Labeau
349                         Rony Elka Vardi, Inc           Daniel Stenson
354                                 Russ Ops LLC      Niki  Russ Federman
368                         SIM Digital New York               Kim Spikes
387                         Sunset Park Farm LLC            Gwen  Schantz
406                      Transmitter Brewing LLC          Anthony Accardi
413                            Ulano Corporation      R. David Eisenbeiss
421                              UTC Corporation              Regina Roch
431  W Architecture & Landscape Architecture LLC            Barbara Wilks
444                        Williams Sonoma, Inc.        Christine Hickman
447              WorldWide Plumbing Supply, Inc.          Surie Lefkowitz

                      company email company phone  \
1                               NaN    2125663000
7               jrproduce@gmail.com    7183708782
16                    info@MEQS.com    2127260700
17         Rlegati@mdc-partners.com    2129931300
46       cryan@american-transit.com    2128578200
54                cory@armadany.com    2677335445
84     johnbattista@yorkstudios.com    3477748500
96          barnaby@casualfilms.com    2127964933
98        edward.p.rooney@chase.com    2126220004
119            durga@dsanddurga.com    9176125566
129   chandra.gopalakrishnan@db.com    2122500109
151        mberry@storagedeluxe.com    2129040403
164       legal@fidelitypayment.com    7187822823
177                anna@gcreate.com    7188528418
178     tfallon@globalterminals.com    7185681714
179              info@corkfloor.com    7187427264
182              macsfish@gmail.com    2122689169
193       sjacobs@haleandhearty.com    2122552400
194         jsitt@vinegarhillhc.com    7188553636
208                info@heyhush.com    7184221537
222         james.carpenter@aol.com    2124314318
252        tom.hoi@lafayette148.com    6467087000
267    ngold@madelainechocolate.com    7189451500
296   r.schwartz@newconceptsllc.com    2126954999
305             aman@takecareof.com    8452229105
311                             NaN    2121112222
326   vmanthripragada@petcarerx.com    5169987041
329        monae@picturefarmpro.com    7182188001
338           jasmine@lightsup.info    7184994209
349              dan@catbirdnyc.com    6469301977
354       niki@russanddaughters.com    2124754880
368  kimspikes@siminternational.com    2126271662
387     gwen@brooklyngrangefarm.com    7184042023
406      ant@transmitterbrewing.com    6463788529
413               grassoe@ulano.com    7182374700
421                             NaN    8606129553
431       bwilks@w-architecture.com    2129813933
444               CHickman@WSGC.com    7187804442
447                sheidya@wwps.com    7188533002

                                         Address           City State  \
1                              100 Church Street             NY    NY
7                                141 Lake Avenue  Staten Island    NY
16                               51 Water Street       Brooklyn    NY
17                               55 Water Street       Brooklyn    NY
46                          One MetroTech Center       Brooklyn    NY
54           141 Flushing Ave, Bldg 77, Unit 404       Brooklyn    NY
84                                1410 Story Ave          Bronx    NY
96           141 Flushing Ave, Bldg 77, Ste #902       Brooklyn    NY
98         Three and Four Chase Metrotech Center       Brooklyn    NY
119              141 Flushing Ave, Bldg 77, #608       Brooklyn    NY
129             4 Chase Metrotech Center, 8th Fl       Brooklyn    NY
151                        26 W 17th St, Ste 801       New York    NY
164  141 Flushing Ave, Bldg 77, Suites 501 & 510       Brooklyn    NY
177           141 Flushing Ave, Bldg 77, Ste 605       Brooklyn    NY
178                              300 Western Ave  Staten Island    NY
179              141 Flushing Ave, Bldg 77, #604       Brooklyn    NY
182                         542 WEST 29TH STREET       New York    NY
193                              75 NINTH AVENUE       New York    NY
194                            12-38 HALL STREET       Brooklyn    NY
208              141 Flushing Ave, Bldg 77, #602       Brooklyn    NY
222                     145 HUDSON ST. 4th Floor       NEW YORK    NY
252           141 Flushing Ave, Bldg 77, 14th Fl       Brooklyn    NY
267                      95-15 BEACH CHANNEL DR.   Far Rockaway    NY
296                         313 West 37th Street       New York    NY
305                         75 Varick St, 9th Fl       New York    NY
311                              140 West Street       New York    NY
326                           1 Metrotech Center       Brooklyn    NY
329                    141 Flushing Ave, Ste 506       Brooklyn    NY
338             141 Flushing Ave, Bldg. 77  #907       Brooklyn    NY
349         141 Flushing Ave, Bldg 77, Unit #903       Brooklyn    NY
354              141 Flushing Ave, Bldg 77, #102       Brooklyn    NY
368                         12 Desbrosses Street       New York    NY
387                63 Flushing Ave, Bldg 3 #1105       Brooklyn    NY
406           141 Flushing Ave, Bldg 77, Ste 104       Brooklyn    NY
413                            268 Bergen Street       Brooklyn    NY
421                              55 Water Street       Brooklyn    NY
431              372-374 Fulton St, 3rd & 4th Fl       Brooklyn    NY
444                              55 Water Street       Brooklyn    NY
447                              125 Lake Avenue  Staten Island    NY

     Postcode                          Industry  \
1       10007                        Commercial
7       10303  Wholesale/Warehouse/Distribution
16      11201                        Commercial
17      11201                        Commercial
46      11201                        Commercial
54      11205                     Manufacturing
84      10473                     Manufacturing
96      11205                     Manufacturing
98      11201                        Commercial
119     11205                     Manufacturing
129     11201                        Commercial
151     10011  Wholesale/Warehouse/Distribution
164     11205                        Commercial
177     11205                     Manufacturing
178     10303                        Commercial
179     11025                     Manufacturing
182     10001                     Manufacturing
193     10011                     Manufacturing
194     11205  Wholesale/Warehouse/Distribution
208     11205                        Commercial
222     10013                     Manufacturing
252     11205  Wholesale/Warehouse/Distribution
267     11693                     Manufacturing
296     10018                     Manufacturing
305     10013  Wholesale/Warehouse/Distribution
311     10007                          Landlord
326     11201                        Commercial
329     11205                        Commercial
338     11205                     Manufacturing
349     11205                     Manufacturing
354     11205                     Manufacturing
368     10013                     Manufacturing
387     11205                     Manufacturing
406     11205                     Manufacturing
413     11217                     Manufacturing
421     11201                        Commercial
431     11201                        Commercial
444     11201  Wholesale/Warehouse/Distribution
447     10303                     Manufacturing

                                        Industry descr  ...  \
1                                            21 Floors  ...
7                            Dist. of prepacked salads  ...
16                                  Management company  ...
17                                         Advertising  ...
46                                           Insurance  ...
54                                      wood furniture  ...
84                        film & television productios  ...
96                 film production and post production  ...
98                                  Financial Services  ...
119                                perfume and candles  ...
129  financial services including securities tradin...  ...
151                         Comprehensive Art Services  ...
164         Merchant payment processing & related svcs  ...
177                     mfg and distribute 3D printers  ...
178   Container Terminal, transportation & warehousing  ...
179                        Manufacturer of color tiles  ...
182                                          MFG. FISH  ...
193                                 MFG. WHS. OF SOUPS  ...
194                Cold storage, dry storage warehouse  ...
208                                     Graphic design  ...
222                         Architectural glass design  ...
252  Mfg & distribute women''s apparel and accessories  ...
267                             MFG. CHOCOLATE NOVELTY  ...
296  manufacturer of leather belts, hat bands and a...  ...
305  Distribution of vitamins, supplements, protein...  ...
311                                                NaN  ...
326             Distributes medicines and pet supplies  ...
329                                   video production  ...
338               Design and Produce Lighting Fixtures  ...
349                                            jewelry  ...
354                                 Food  Manufacturer  ...
368              motion picture and tv post-production  ...
387                  greenhouse vegetables and flowers  ...
406                                        beer brewer  ...
413   Screen printing and draft graphics arts industry  ...
421  Commercial company that provides product servi...  ...
431              Architecture & landscape architecture  ...
444                 high quality products for the home  ...
447      Plumbing Fixtures, Parts & Supplies, Plumbers  ...

    Savings from beginning receiving benefits        Borough   Latitude  \
1                                  4423698.05       New York  40.712968
7                                    59681.70  Staten Island  40.633153
16                                   10657.15       Brooklyn  40.703304
17                                   30061.25       Brooklyn  40.703301
46                                  331784.18       Brooklyn  40.694059
54                                    7810.11       Brooklyn  40.697863
84                                   68441.72          Bronx  40.820972
96                                    2606.63       Brooklyn  40.697863
98                                 3098630.05       Brooklyn  40.694059
119                                   2047.66       Brooklyn  40.697863
129                                  64256.13       Brooklyn  40.694059
151                                   5287.17       New York  40.738349
164                                  16510.55       Brooklyn  40.697863
177                                   3698.07       Brooklyn  40.697863
178                                1188739.12  Staten Island  40.633645
179                                   4060.38       Brooklyn  40.697863
182                                  55262.97       New York  40.752098
193                                 682373.78       New York  40.741876
194                                 328295.65       Brooklyn  40.697200
208                                   5821.14       Brooklyn  40.697863
222                                  16400.06       New York  40.721073
252                                  99681.50       Brooklyn  40.697863
267                                   9142.26         Queens  40.587549
296                                  19806.86       New York  40.754384
305                                  10726.10       New York  40.723217
311                                 398668.88       New York  40.713843
326                                  14912.68       Brooklyn  40.693463
329                                   6762.69       Brooklyn  40.697863
338                                   2501.52       Brooklyn  40.697863
349                                  18667.55       Brooklyn  40.697863
354                                  31813.35       Brooklyn  40.697863
368                                 104844.84       New York  40.723365
387                                   1926.51       Brooklyn  40.698020
406                                  18901.61       Brooklyn  40.697863
413                                 703087.79       Brooklyn  40.683922
421                                  60210.91       Brooklyn  40.703301
431                                   3757.68       Brooklyn  40.691597
444                                  56547.18       Brooklyn  40.703301
447                                  20487.73  Staten Island  40.633518

     Longitude Community Board  Council District  Census Tract        BIN  \
1   -74.009490           101.0               1.0          21.0  1001409.0
7   -74.150999           501.0              49.0         239.0  5146740.0
16  -73.992156           302.0              33.0          21.0  3000000.0
17  -73.992047           302.0              33.0          21.0  3000019.0
46  -73.985741           302.0              33.0          11.0  3000000.0
54  -73.971138           302.0              33.0         543.0  3335143.0
84  -73.882556           209.0              17.0          28.0  2000000.0
96  -73.971138           302.0              33.0         543.0  3335143.0
98  -73.985741           302.0              33.0          11.0  3000000.0
119 -73.971138           302.0              33.0         543.0  3335143.0
129 -73.985741           302.0              33.0          11.0  3000000.0
151 -73.993277           105.0               3.0          54.0  1015400.0
164 -73.971138           302.0              33.0         543.0  3335143.0
177 -73.971138           302.0              33.0         543.0  3335143.0
178 -74.182637           501.0              49.0         323.0  5000000.0
179 -73.971138           302.0              33.0         543.0  3335143.0
182 -74.002999           104.0               3.0          99.0  1012437.0
193 -74.004713           104.0               3.0          83.0  1012541.0
194 -73.966663           302.0              35.0         543.0  3334438.0
208 -73.971138           302.0              33.0         543.0  3335143.0
222 -74.008398           101.0               1.0          39.0  1002803.0
252 -73.971138           302.0              33.0         543.0  3335143.0
267 -73.819012           414.0              32.0       94201.0  4303676.0
296 -73.992742           104.0               3.0         111.0  1013618.0
305 -74.006227           102.0               1.0          37.0  1002934.0
311 -74.013790           101.0               1.0          21.0  1001228.0
326 -73.987227           302.0              33.0          11.0  3319418.0
329 -73.971138           302.0              33.0         543.0  3335143.0
338 -73.971138           302.0              33.0         543.0  3335143.0
349 -73.971138           302.0              33.0         543.0  3335143.0
354 -73.971138           302.0              33.0         543.0  3335143.0
368 -74.008756           101.0               1.0          39.0  1002932.0
387 -73.974986           302.0              33.0         543.0  3335129.0
406 -73.971138           302.0              33.0         543.0  3335143.0
413 -73.983303           302.0              33.0         127.0  3005967.0
421 -73.992047           302.0              33.0          21.0  3000019.0
431 -73.987714           302.0              33.0          37.0  3000426.0
444 -73.992047           302.0              33.0          21.0  3000019.0
447 -74.150942           501.0              49.0         239.0  5107122.0

              BBL                                                NTA
1    1.001250e+09             SoHo-TriBeCa-Civic Center-Little Italy
7    5.011610e+09  Mariner's Harbor-Arlington-Port Ivory-Granitev...
16   3.000260e+09   DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill
17   3.000260e+09   DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill
46   3.001420e+09   DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill
54   3.020230e+09                         park-cemetery-etc-Brooklyn
84   2.036220e+09    Soundview-Castle Hill-Clason Point-Harding Park
96   3.020230e+09                         park-cemetery-etc-Brooklyn
98   3.001420e+09   DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill
119  3.020230e+09                         park-cemetery-etc-Brooklyn
129  3.001420e+09   DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill
151  1.008180e+09         Hudson Yards-Chelsea-Flatiron-Union Square
164  3.020230e+09                         park-cemetery-etc-Brooklyn
177  3.020230e+09                         park-cemetery-etc-Brooklyn
178  5.014100e+09  Mariner's Harbor-Arlington-Port Ivory-Granitev...
179  3.020230e+09                         park-cemetery-etc-Brooklyn
182  1.007000e+09         Hudson Yards-Chelsea-Flatiron-Union Square
193  1.007130e+09         Hudson Yards-Chelsea-Flatiron-Union Square
194  3.018750e+09                         park-cemetery-etc-Brooklyn
208  3.020230e+09                         park-cemetery-etc-Brooklyn
222  1.002148e+09             SoHo-TriBeCa-Civic Center-Little Italy
252  3.020230e+09                         park-cemetery-etc-Brooklyn
267  4.161510e+09  Breezy Point-Belle Harbor-Rockaway Park-Broad ...
296  1.007610e+09         Hudson Yards-Chelsea-Flatiron-Union Square
305  1.002260e+09             SoHo-TriBeCa-Civic Center-Little Italy
311  1.000848e+09             SoHo-TriBeCa-Civic Center-Little Italy
326  3.001470e+09   DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill
329  3.020230e+09                         park-cemetery-etc-Brooklyn